// One-off script: fetches Greek airports, marinas, ports, hospitals from
// OpenStreetMap via the Overpass API and writes src/data/pois-data.ts.
//
// Run with: bun run scripts/build-pois.ts
// Commit the resulting src/data/pois-data.ts.

import { writeFileSync } from "node:fs";

type Cat = "port" | "marina" | "hospital" | "airport";

const QUERY = `
[out:json][timeout:90];
area["ISO3166-1"="GR"][admin_level=2]->.gr;
(
  node["aeroway"="aerodrome"](area.gr);
  node["leisure"="marina"](area.gr);
  node["harbour"="yes"](area.gr);
  node["amenity"="ferry_terminal"](area.gr);
  node["amenity"="hospital"](area.gr);
  way["aeroway"="aerodrome"](area.gr);
  way["leisure"="marina"](area.gr);
  way["amenity"="hospital"](area.gr);
);
out center tags;
`;

interface OsmEl {
  type: string;
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

function classify(tags: Record<string, string>): Cat | null {
  if (tags.aeroway === "aerodrome") {
    // Skip tiny airstrips. Keep international, regional, and municipal.
    if (tags.aerodrome === "private" || tags.aerodrome === "airfield") return null;
    if (!tags.name) return null;
    return "airport";
  }
  if (tags.leisure === "marina") return "marina";
  if (tags.harbour === "yes" || tags.amenity === "ferry_terminal") return "port";
  if (tags.amenity === "hospital") {
    // Filter to substantial hospitals only: must have name and not be a clinic.
    if (!tags.name) return null;
    if (tags["healthcare:speciality"]) return null;
    if (tags.healthcare === "clinic" || tags.healthcare === "doctor") return null;
    return "hospital";
  }
  return null;
}

function cityFrom(tags: Record<string, string>): string {
  return (
    tags["addr:city"] ||
    tags["addr:suburb"] ||
    tags["is_in:municipality"] ||
    tags["is_in"] ||
    ""
  );
}

async function main() {
  console.log("Querying Overpass...");
  const res = await fetch("https://overpass-api.de/api/interpreter", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "greecevest-poi-builder/1.0 (contact: dev@greecevest.local)",
      Accept: "application/json",
    },
    body: "data=" + encodeURIComponent(QUERY),
  });
  if (!res.ok) {
    throw new Error("Overpass failed: " + res.status + " " + (await res.text()));
  }
  const json = (await res.json()) as { elements: OsmEl[] };
  console.log("Got " + json.elements.length + " raw elements");

  const seen = new Set<string>();
  const out: Array<{ name: string; lat: number; lon: number; category: Cat; city: string }> = [];

  for (const el of json.elements) {
    const tags = el.tags || {};
    const cat = classify(tags);
    if (!cat) continue;
    const lat = el.lat ?? el.center?.lat;
    const lon = el.lon ?? el.center?.lon;
    if (lat == null || lon == null) continue;
    const name = (tags["name:en"] || tags.name || "").trim();
    if (!name) continue;
    // Dedupe nearby duplicates (same name + category within ~500m).
    const key = cat + "|" + name.toLowerCase() + "|" + lat.toFixed(2) + "|" + lon.toFixed(2);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({
      name,
      lat: Number(lat.toFixed(4)),
      lon: Number(lon.toFixed(4)),
      category: cat,
      city: cityFrom(tags),
    });
  }

  // Sort: airport, port, marina, hospital, then name.
  const order: Record<Cat, number> = { airport: 0, port: 1, marina: 2, hospital: 3 };
  out.sort((a, b) => order[a.category] - order[b.category] || a.name.localeCompare(b.name));

  console.log("Kept " + out.length + " POIs");
  const counts = out.reduce<Record<string, number>>((acc, p) => {
    acc[p.category] = (acc[p.category] || 0) + 1;
    return acc;
  }, {});
  console.log("By category:", counts);

  const file =
    `// Auto-generated by scripts/build-pois.ts from OpenStreetMap (Overpass API).
// Do not hand-edit. Re-run the script and commit the result.

export type POICategory = "port" | "marina" | "hospital" | "airport";
export interface POI { name: string; lat: number; lon: number; category: POICategory; city: string; }

export const poisData: POI[] = ` +
    JSON.stringify(out, null, 2) +
    ";\n";

  writeFileSync("src/data/pois-data.ts", file);
  console.log("Wrote src/data/pois-data.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
