/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentMapRouteImport } from './routes/investment-map'
import { Route as GigsRouteImport } from './routes/gigs'
import { Route as ElRouteImport } from './routes/el'
import { Route as DataProtectionRouteImport } from './routes/data-protection'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as ProfessionalsIndexRouteImport } from './routes/professionals.index'
import { Route as GigsIndexRouteImport } from './routes/gigs.index'
import { Route as ElIndexRouteImport } from './routes/el.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ProfessionalsIdRouteImport } from './routes/professionals.$id'
import { Route as GigsPostRouteImport } from './routes/gigs.post'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as ElTermsRouteImport } from './routes/el.terms'
import { Route as ElSignupRouteImport } from './routes/el.signup'
import { Route as ElPropertiesRouteImport } from './routes/el.properties'
import { Route as ElProfessionalsRouteImport } from './routes/el.professionals'
import { Route as ElPrivacyPolicyRouteImport } from './routes/el.privacy-policy'
import { Route as ElLoginRouteImport } from './routes/el.login'
import { Route as ElInvestmentMapRouteImport } from './routes/el.investment-map'
import { Route as ElGigsRouteImport } from './routes/el.gigs'
import { Route as ElDataProtectionRouteImport } from './routes/el.data-protection'
import { Route as ElContactUsRouteImport } from './routes/el.contact-us'
import { Route as ElAboutUsRouteImport } from './routes/el.about-us'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as ElPropertiesIndexRouteImport } from './routes/el.properties.index'
import { Route as ElGigsIndexRouteImport } from './routes/el.gigs.index'
import { Route as ElPropertiesIdRouteImport } from './routes/el.properties.$id'
import { Route as ElProfessionalsIdRouteImport } from './routes/el.professionals.$id'
import { Route as ElGigsPostRouteImport } from './routes/el.gigs.post'
import { Route as ElGigsIdRouteImport } from './routes/el.gigs.$id'
import { Route as ElAgenciesSlugRouteImport } from './routes/el.agencies.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentMapRoute = InvestmentMapRouteImport.update({
  id: '/investment-map',
  path: '/investment-map',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsRoute = GigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProtectionRoute = DataProtectionRouteImport.update({
  id: '/data-protection',
  path: '/data-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const ProfessionalsIndexRoute = ProfessionalsIndexRouteImport.update({
  id: '/professionals/',
  path: '/professionals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GigsRoute,
} as any)
const ElIndexRoute = ElIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const ProfessionalsIdRoute = ProfessionalsIdRouteImport.update({
  id: '/professionals/$id',
  path: '/professionals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsPostRoute = GigsPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => GigsRoute,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GigsRoute,
} as any)
const ElTermsRoute = ElTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ElRoute,
} as any)
const ElSignupRoute = ElSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => ElRoute,
} as any)
const ElPropertiesRoute = ElPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => ElRoute,
} as any)
const ElProfessionalsRoute = ElProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => ElRoute,
} as any)
const ElPrivacyPolicyRoute = ElPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => ElRoute,
} as any)
const ElLoginRoute = ElLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ElRoute,
} as any)
const ElInvestmentMapRoute = ElInvestmentMapRouteImport.update({
  id: '/investment-map',
  path: '/investment-map',
  getParentRoute: () => ElRoute,
} as any)
const ElGigsRoute = ElGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => ElRoute,
} as any)
const ElDataProtectionRoute = ElDataProtectionRouteImport.update({
  id: '/data-protection',
  path: '/data-protection',
  getParentRoute: () => ElRoute,
} as any)
const ElContactUsRoute = ElContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => ElRoute,
} as any)
const ElAboutUsRoute = ElAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => ElRoute,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/agencies/$slug',
  path: '/agencies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ElPropertiesIndexRoute = ElPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElPropertiesRoute,
} as any)
const ElGigsIndexRoute = ElGigsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElGigsRoute,
} as any)
const ElPropertiesIdRoute = ElPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ElPropertiesRoute,
} as any)
const ElProfessionalsIdRoute = ElProfessionalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ElProfessionalsRoute,
} as any)
const ElGigsPostRoute = ElGigsPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => ElGigsRoute,
} as any)
const ElGigsIdRoute = ElGigsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ElGigsRoute,
} as any)
const ElAgenciesSlugRoute = ElAgenciesSlugRouteImport.update({
  id: '/agencies/$slug',
  path: '/agencies/$slug',
  getParentRoute: () => ElRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/data-protection': typeof DataProtectionRoute
  '/el': typeof ElRouteWithChildren
  '/gigs': typeof GigsRouteWithChildren
  '/investment-map': typeof InvestmentMapRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/el/about-us': typeof ElAboutUsRoute
  '/el/contact-us': typeof ElContactUsRoute
  '/el/data-protection': typeof ElDataProtectionRoute
  '/el/gigs': typeof ElGigsRouteWithChildren
  '/el/investment-map': typeof ElInvestmentMapRoute
  '/el/login': typeof ElLoginRoute
  '/el/privacy-policy': typeof ElPrivacyPolicyRoute
  '/el/professionals': typeof ElProfessionalsRouteWithChildren
  '/el/properties': typeof ElPropertiesRouteWithChildren
  '/el/signup': typeof ElSignupRoute
  '/el/terms': typeof ElTermsRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/post': typeof GigsPostRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/el/': typeof ElIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/professionals/': typeof ProfessionalsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/el/agencies/$slug': typeof ElAgenciesSlugRoute
  '/el/gigs/$id': typeof ElGigsIdRoute
  '/el/gigs/post': typeof ElGigsPostRoute
  '/el/professionals/$id': typeof ElProfessionalsIdRoute
  '/el/properties/$id': typeof ElPropertiesIdRoute
  '/el/gigs/': typeof ElGigsIndexRoute
  '/el/properties/': typeof ElPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/data-protection': typeof DataProtectionRoute
  '/investment-map': typeof InvestmentMapRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/el/about-us': typeof ElAboutUsRoute
  '/el/contact-us': typeof ElContactUsRoute
  '/el/data-protection': typeof ElDataProtectionRoute
  '/el/investment-map': typeof ElInvestmentMapRoute
  '/el/login': typeof ElLoginRoute
  '/el/privacy-policy': typeof ElPrivacyPolicyRoute
  '/el/professionals': typeof ElProfessionalsRouteWithChildren
  '/el/signup': typeof ElSignupRoute
  '/el/terms': typeof ElTermsRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/post': typeof GigsPostRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/el': typeof ElIndexRoute
  '/gigs': typeof GigsIndexRoute
  '/professionals': typeof ProfessionalsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/el/agencies/$slug': typeof ElAgenciesSlugRoute
  '/el/gigs/$id': typeof ElGigsIdRoute
  '/el/gigs/post': typeof ElGigsPostRoute
  '/el/professionals/$id': typeof ElProfessionalsIdRoute
  '/el/properties/$id': typeof ElPropertiesIdRoute
  '/el/gigs': typeof ElGigsIndexRoute
  '/el/properties': typeof ElPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/data-protection': typeof DataProtectionRoute
  '/el': typeof ElRouteWithChildren
  '/gigs': typeof GigsRouteWithChildren
  '/investment-map': typeof InvestmentMapRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/el/about-us': typeof ElAboutUsRoute
  '/el/contact-us': typeof ElContactUsRoute
  '/el/data-protection': typeof ElDataProtectionRoute
  '/el/gigs': typeof ElGigsRouteWithChildren
  '/el/investment-map': typeof ElInvestmentMapRoute
  '/el/login': typeof ElLoginRoute
  '/el/privacy-policy': typeof ElPrivacyPolicyRoute
  '/el/professionals': typeof ElProfessionalsRouteWithChildren
  '/el/properties': typeof ElPropertiesRouteWithChildren
  '/el/signup': typeof ElSignupRoute
  '/el/terms': typeof ElTermsRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/post': typeof GigsPostRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/el/': typeof ElIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/professionals/': typeof ProfessionalsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/el/agencies/$slug': typeof ElAgenciesSlugRoute
  '/el/gigs/$id': typeof ElGigsIdRoute
  '/el/gigs/post': typeof ElGigsPostRoute
  '/el/professionals/$id': typeof ElProfessionalsIdRoute
  '/el/properties/$id': typeof ElPropertiesIdRoute
  '/el/gigs/': typeof ElGigsIndexRoute
  '/el/properties/': typeof ElPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/data-protection'
    | '/el'
    | '/gigs'
    | '/investment-map'
    | '/login'
    | '/privacy-policy'
    | '/properties'
    | '/signup'
    | '/terms'
    | '/agencies/$slug'
    | '/el/about-us'
    | '/el/contact-us'
    | '/el/data-protection'
    | '/el/gigs'
    | '/el/investment-map'
    | '/el/login'
    | '/el/privacy-policy'
    | '/el/professionals'
    | '/el/properties'
    | '/el/signup'
    | '/el/terms'
    | '/gigs/$id'
    | '/gigs/post'
    | '/professionals/$id'
    | '/properties/$id'
    | '/el/'
    | '/gigs/'
    | '/professionals/'
    | '/properties/'
    | '/el/agencies/$slug'
    | '/el/gigs/$id'
    | '/el/gigs/post'
    | '/el/professionals/$id'
    | '/el/properties/$id'
    | '/el/gigs/'
    | '/el/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/data-protection'
    | '/investment-map'
    | '/login'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/agencies/$slug'
    | '/el/about-us'
    | '/el/contact-us'
    | '/el/data-protection'
    | '/el/investment-map'
    | '/el/login'
    | '/el/privacy-policy'
    | '/el/professionals'
    | '/el/signup'
    | '/el/terms'
    | '/gigs/$id'
    | '/gigs/post'
    | '/professionals/$id'
    | '/properties/$id'
    | '/el'
    | '/gigs'
    | '/professionals'
    | '/properties'
    | '/el/agencies/$slug'
    | '/el/gigs/$id'
    | '/el/gigs/post'
    | '/el/professionals/$id'
    | '/el/properties/$id'
    | '/el/gigs'
    | '/el/properties'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/data-protection'
    | '/el'
    | '/gigs'
    | '/investment-map'
    | '/login'
    | '/privacy-policy'
    | '/properties'
    | '/signup'
    | '/terms'
    | '/agencies/$slug'
    | '/el/about-us'
    | '/el/contact-us'
    | '/el/data-protection'
    | '/el/gigs'
    | '/el/investment-map'
    | '/el/login'
    | '/el/privacy-policy'
    | '/el/professionals'
    | '/el/properties'
    | '/el/signup'
    | '/el/terms'
    | '/gigs/$id'
    | '/gigs/post'
    | '/professionals/$id'
    | '/properties/$id'
    | '/el/'
    | '/gigs/'
    | '/professionals/'
    | '/properties/'
    | '/el/agencies/$slug'
    | '/el/gigs/$id'
    | '/el/gigs/post'
    | '/el/professionals/$id'
    | '/el/properties/$id'
    | '/el/gigs/'
    | '/el/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  DataProtectionRoute: typeof DataProtectionRoute
  ElRoute: typeof ElRouteWithChildren
  GigsRoute: typeof GigsRouteWithChildren
  InvestmentMapRoute: typeof InvestmentMapRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  ProfessionalsIdRoute: typeof ProfessionalsIdRoute
  ProfessionalsIndexRoute: typeof ProfessionalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-map': {
      id: '/investment-map'
      path: '/investment-map'
      fullPath: '/investment-map'
      preLoaderRoute: typeof InvestmentMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs': {
      id: '/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof GigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-protection': {
      id: '/data-protection'
      path: '/data-protection'
      fullPath: '/data-protection'
      preLoaderRoute: typeof DataProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/professionals/': {
      id: '/professionals/'
      path: '/professionals'
      fullPath: '/professionals/'
      preLoaderRoute: typeof ProfessionalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof GigsRoute
    }
    '/el/': {
      id: '/el/'
      path: '/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/professionals/$id': {
      id: '/professionals/$id'
      path: '/professionals/$id'
      fullPath: '/professionals/$id'
      preLoaderRoute: typeof ProfessionalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/post': {
      id: '/gigs/post'
      path: '/post'
      fullPath: '/gigs/post'
      preLoaderRoute: typeof GigsPostRouteImport
      parentRoute: typeof GigsRoute
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof GigsRoute
    }
    '/el/terms': {
      id: '/el/terms'
      path: '/terms'
      fullPath: '/el/terms'
      preLoaderRoute: typeof ElTermsRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/signup': {
      id: '/el/signup'
      path: '/signup'
      fullPath: '/el/signup'
      preLoaderRoute: typeof ElSignupRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/properties': {
      id: '/el/properties'
      path: '/properties'
      fullPath: '/el/properties'
      preLoaderRoute: typeof ElPropertiesRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/professionals': {
      id: '/el/professionals'
      path: '/professionals'
      fullPath: '/el/professionals'
      preLoaderRoute: typeof ElProfessionalsRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/privacy-policy': {
      id: '/el/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/el/privacy-policy'
      preLoaderRoute: typeof ElPrivacyPolicyRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/login': {
      id: '/el/login'
      path: '/login'
      fullPath: '/el/login'
      preLoaderRoute: typeof ElLoginRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/investment-map': {
      id: '/el/investment-map'
      path: '/investment-map'
      fullPath: '/el/investment-map'
      preLoaderRoute: typeof ElInvestmentMapRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/gigs': {
      id: '/el/gigs'
      path: '/gigs'
      fullPath: '/el/gigs'
      preLoaderRoute: typeof ElGigsRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/data-protection': {
      id: '/el/data-protection'
      path: '/data-protection'
      fullPath: '/el/data-protection'
      preLoaderRoute: typeof ElDataProtectionRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/contact-us': {
      id: '/el/contact-us'
      path: '/contact-us'
      fullPath: '/el/contact-us'
      preLoaderRoute: typeof ElContactUsRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/about-us': {
      id: '/el/about-us'
      path: '/about-us'
      fullPath: '/el/about-us'
      preLoaderRoute: typeof ElAboutUsRouteImport
      parentRoute: typeof ElRoute
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/agencies/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/properties/': {
      id: '/el/properties/'
      path: '/'
      fullPath: '/el/properties/'
      preLoaderRoute: typeof ElPropertiesIndexRouteImport
      parentRoute: typeof ElPropertiesRoute
    }
    '/el/gigs/': {
      id: '/el/gigs/'
      path: '/'
      fullPath: '/el/gigs/'
      preLoaderRoute: typeof ElGigsIndexRouteImport
      parentRoute: typeof ElGigsRoute
    }
    '/el/properties/$id': {
      id: '/el/properties/$id'
      path: '/$id'
      fullPath: '/el/properties/$id'
      preLoaderRoute: typeof ElPropertiesIdRouteImport
      parentRoute: typeof ElPropertiesRoute
    }
    '/el/professionals/$id': {
      id: '/el/professionals/$id'
      path: '/$id'
      fullPath: '/el/professionals/$id'
      preLoaderRoute: typeof ElProfessionalsIdRouteImport
      parentRoute: typeof ElProfessionalsRoute
    }
    '/el/gigs/post': {
      id: '/el/gigs/post'
      path: '/post'
      fullPath: '/el/gigs/post'
      preLoaderRoute: typeof ElGigsPostRouteImport
      parentRoute: typeof ElGigsRoute
    }
    '/el/gigs/$id': {
      id: '/el/gigs/$id'
      path: '/$id'
      fullPath: '/el/gigs/$id'
      preLoaderRoute: typeof ElGigsIdRouteImport
      parentRoute: typeof ElGigsRoute
    }
    '/el/agencies/$slug': {
      id: '/el/agencies/$slug'
      path: '/agencies/$slug'
      fullPath: '/el/agencies/$slug'
      preLoaderRoute: typeof ElAgenciesSlugRouteImport
      parentRoute: typeof ElRoute
    }
  }
}

interface ElGigsRouteChildren {
  ElGigsIdRoute: typeof ElGigsIdRoute
  ElGigsPostRoute: typeof ElGigsPostRoute
  ElGigsIndexRoute: typeof ElGigsIndexRoute
}

const ElGigsRouteChildren: ElGigsRouteChildren = {
  ElGigsIdRoute: ElGigsIdRoute,
  ElGigsPostRoute: ElGigsPostRoute,
  ElGigsIndexRoute: ElGigsIndexRoute,
}

const ElGigsRouteWithChildren =
  ElGigsRoute._addFileChildren(ElGigsRouteChildren)

interface ElProfessionalsRouteChildren {
  ElProfessionalsIdRoute: typeof ElProfessionalsIdRoute
}

const ElProfessionalsRouteChildren: ElProfessionalsRouteChildren = {
  ElProfessionalsIdRoute: ElProfessionalsIdRoute,
}

const ElProfessionalsRouteWithChildren = ElProfessionalsRoute._addFileChildren(
  ElProfessionalsRouteChildren,
)

interface ElPropertiesRouteChildren {
  ElPropertiesIdRoute: typeof ElPropertiesIdRoute
  ElPropertiesIndexRoute: typeof ElPropertiesIndexRoute
}

const ElPropertiesRouteChildren: ElPropertiesRouteChildren = {
  ElPropertiesIdRoute: ElPropertiesIdRoute,
  ElPropertiesIndexRoute: ElPropertiesIndexRoute,
}

const ElPropertiesRouteWithChildren = ElPropertiesRoute._addFileChildren(
  ElPropertiesRouteChildren,
)

interface ElRouteChildren {
  ElAboutUsRoute: typeof ElAboutUsRoute
  ElContactUsRoute: typeof ElContactUsRoute
  ElDataProtectionRoute: typeof ElDataProtectionRoute
  ElGigsRoute: typeof ElGigsRouteWithChildren
  ElInvestmentMapRoute: typeof ElInvestmentMapRoute
  ElLoginRoute: typeof ElLoginRoute
  ElPrivacyPolicyRoute: typeof ElPrivacyPolicyRoute
  ElProfessionalsRoute: typeof ElProfessionalsRouteWithChildren
  ElPropertiesRoute: typeof ElPropertiesRouteWithChildren
  ElSignupRoute: typeof ElSignupRoute
  ElTermsRoute: typeof ElTermsRoute
  ElIndexRoute: typeof ElIndexRoute
  ElAgenciesSlugRoute: typeof ElAgenciesSlugRoute
}

const ElRouteChildren: ElRouteChildren = {
  ElAboutUsRoute: ElAboutUsRoute,
  ElContactUsRoute: ElContactUsRoute,
  ElDataProtectionRoute: ElDataProtectionRoute,
  ElGigsRoute: ElGigsRouteWithChildren,
  ElInvestmentMapRoute: ElInvestmentMapRoute,
  ElLoginRoute: ElLoginRoute,
  ElPrivacyPolicyRoute: ElPrivacyPolicyRoute,
  ElProfessionalsRoute: ElProfessionalsRouteWithChildren,
  ElPropertiesRoute: ElPropertiesRouteWithChildren,
  ElSignupRoute: ElSignupRoute,
  ElTermsRoute: ElTermsRoute,
  ElIndexRoute: ElIndexRoute,
  ElAgenciesSlugRoute: ElAgenciesSlugRoute,
}

const ElRouteWithChildren = ElRoute._addFileChildren(ElRouteChildren)

interface GigsRouteChildren {
  GigsIdRoute: typeof GigsIdRoute
  GigsPostRoute: typeof GigsPostRoute
  GigsIndexRoute: typeof GigsIndexRoute
}

const GigsRouteChildren: GigsRouteChildren = {
  GigsIdRoute: GigsIdRoute,
  GigsPostRoute: GigsPostRoute,
  GigsIndexRoute: GigsIndexRoute,
}

const GigsRouteWithChildren = GigsRoute._addFileChildren(GigsRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  DataProtectionRoute: DataProtectionRoute,
  ElRoute: ElRouteWithChildren,
  GigsRoute: GigsRouteWithChildren,
  InvestmentMapRoute: InvestmentMapRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AgenciesSlugRoute: AgenciesSlugRoute,
  ProfessionalsIdRoute: ProfessionalsIdRoute,
  ProfessionalsIndexRoute: ProfessionalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
